export const seedActors = [
  { name: "Shah Rukh Khan", popularityScore: 100, aliases: ["SRK", "Shahrukh Khan", "King Khan", "Badshah"] },
  { name: "Salman Khan", popularityScore: 98, aliases: ["Bhaijaan", "Sallu", "Bhai"] },
  { name: "Aamir Khan", popularityScore: 96, aliases: ["Mr Perfectionist", "AK"] },
  { name: "Amitabh Bachchan", popularityScore: 99, aliases: ["Big B", "Amitabh", "Shahenshah"] },
  { name: "Akshay Kumar", popularityScore: 95, aliases: ["Khiladi", "Akki"] },
  { name: "Hrithik Roshan", popularityScore: 94, aliases: ["Greek God", "Hrithik", "Duggu"] },
  { name: "Ranbir Kapoor", popularityScore: 93, aliases: ["RK", "Ranbir"] },
  { name: "Deepika Padukone", popularityScore: 95, aliases: ["Deepika", "DP"] },
  { name: "Priyanka Chopra", popularityScore: 94, aliases: ["Priyanka", "PC", "Piggy Chops"] },
  { name: "Katrina Kaif", popularityScore: 92, aliases: ["Katrina", "Kat"] },
  { name: "Kareena Kapoor Khan", popularityScore: 93, aliases: ["Kareena", "Bebo"] },
  { name: "Alia Bhatt", popularityScore: 92, aliases: ["Alia", "Aloo"] },
  { name: "Ranveer Singh", popularityScore: 91, aliases: ["Ranveer", "RS"] },
  { name: "Ajay Devgn", popularityScore: 90, aliases: ["Ajay", "Ajay Devgan"] },
  { name: "Shahid Kapoor", popularityScore: 89, aliases: ["Shahid", "Sasha"] },
  { name: "Anushka Sharma", popularityScore: 88, aliases: ["Anushka", "Nushki"] },
  { name: "Varun Dhawan", popularityScore: 87, aliases: ["Varun", "VD"] },
  { name: "Sidharth Malhotra", popularityScore: 85, aliases: ["Sidharth", "Sid"] },
  { name: "Tiger Shroff", popularityScore: 84, aliases: ["Tiger", "Jai"] },
  { name: "Shraddha Kapoor", popularityScore: 86, aliases: ["Shraddha", "Shradz"] },
  { name: "Kriti Sanon", popularityScore: 83, aliases: ["Kriti"] },
  { name: "Kiara Advani", popularityScore: 82, aliases: ["Kiara"] },
  { name: "Janhvi Kapoor", popularityScore: 80, aliases: ["Janhvi"] },
  { name: "Sara Ali Khan", popularityScore: 81, aliases: ["Sara"] },
  { name: "Ananya Panday", popularityScore: 79, aliases: ["Ananya"] },
  { name: "Ayushmann Khurrana", popularityScore: 87, aliases: ["Ayushmann"] },
  { name: "Rajkummar Rao", popularityScore: 86, aliases: ["Rajkummar", "Rao"] },
  { name: "Vicky Kaushal", popularityScore: 88, aliases: ["Vicky"] },
  { name: "Kartik Aaryan", popularityScore: 85, aliases: ["Kartik"] },
  { name: "Nawazuddin Siddiqui", popularityScore: 84, aliases: ["Nawazuddin", "Nawaz"] },
  { name: "Pankaj Tripathi", popularityScore: 85, aliases: ["Pankaj", "Tripathi"] },
  { name: "Irrfan Khan", popularityScore: 90, aliases: ["Irrfan", "Irfan Khan"] },
  { name: "Manoj Bajpayee", popularityScore: 86, aliases: ["Manoj"] },
  { name: "Bhumi Pednekar", popularityScore: 82, aliases: ["Bhumi"] },
  { name: "Taapsee Pannu", popularityScore: 83, aliases: ["Taapsee"] },
  { name: "Kangana Ranaut", popularityScore: 87, aliases: ["Kangana"] },
  { name: "Sonam Kapoor", popularityScore: 82, aliases: ["Sonam"] },
  { name: "Jacqueline Fernandez", popularityScore: 81, aliases: ["Jacqueline", "Jacky"] },
  { name: "Disha Patani", popularityScore: 80, aliases: ["Disha"] },
  { name: "Madhuri Dixit", popularityScore: 92, aliases: ["Madhuri", "Dhak Dhak Girl"] },
  { name: "Kajol", popularityScore: 91, aliases: ["Kajol Devgn"] },
  { name: "Rani Mukerji", popularityScore: 90, aliases: ["Rani"] },
  { name: "Preity Zinta", popularityScore: 88, aliases: ["Preity"] },
  { name: "Aishwarya Rai Bachchan", popularityScore: 92, aliases: ["Aishwarya", "Ash"] },
  { name: "Saif Ali Khan", popularityScore: 88, aliases: ["Saif", "Chote Nawab"] },
  { name: "Sanjay Dutt", popularityScore: 87, aliases: ["Sanju", "Baba"] },
  { name: "Sunny Deol", popularityScore: 86, aliases: ["Sunny", "Dhai Kilo Ka Haath"] },
  { name: "Suniel Shetty", popularityScore: 84, aliases: ["Suniel", "Anna"] },
  { name: "Bobby Deol", popularityScore: 83, aliases: ["Bobby"] },
  { name: "John Abraham", popularityScore: 85, aliases: ["John"] },
  { name: "Abhishek Bachchan", popularityScore: 84, aliases: ["Abhishek", "AB Junior"] },
  { name: "Boman Irani", popularityScore: 82, aliases: ["Boman"] },
  { name: "Anupam Kher", popularityScore: 83, aliases: ["Anupam"] },
  { name: "Om Puri", popularityScore: 85, aliases: ["Om"] },
  { name: "Naseeruddin Shah", popularityScore: 88, aliases: ["Naseeruddin", "Naseer"] },
  { name: "Paresh Rawal", popularityScore: 86, aliases: ["Paresh"] },
  { name: "Johnny Lever", popularityScore: 84, aliases: ["Johnny"] },
  { name: "Arshad Warsi", popularityScore: 83, aliases: ["Arshad"] },
  { name: "Riteish Deshmukh", popularityScore: 82, aliases: ["Riteish"] },
  { name: "Neetu Singh", popularityScore: 81, aliases: ["Neetu"] },
  { name: "Rekha", popularityScore: 89, aliases: ["Rekha"] },
  { name: "Hema Malini", popularityScore: 88, aliases: ["Hema", "Dream Girl"] },
  { name: "Sridevi", popularityScore: 91, aliases: ["Sridevi"] },
  { name: "Juhi Chawla", popularityScore: 87, aliases: ["Juhi"] },
  { name: "Karishma Kapoor", popularityScore: 86, aliases: ["Karishma", "Lolo"] },
  { name: "Tabu", popularityScore: 88, aliases: ["Tabassum"] },
  { name: "Urmila Matondkar", popularityScore: 85, aliases: ["Urmila"] },
  { name: "Shilpa Shetty", popularityScore: 84, aliases: ["Shilpa"] },
  { name: "Bipasha Basu", popularityScore: 83, aliases: ["Bipasha"] },
  { name: "Lara Dutta", popularityScore: 82, aliases: ["Lara"] },
  { name: "Sushmita Sen", popularityScore: 85, aliases: ["Sushmita"] },
  { name: "Raveena Tandon", popularityScore: 84, aliases: ["Raveena"] },
  { name: "Sonakshi Sinha", popularityScore: 83, aliases: ["Sonakshi"] },
  { name: "Parineeti Chopra", popularityScore: 82, aliases: ["Parineeti"] },
  { name: "Ileana DCruz", popularityScore: 81, aliases: ["Ileana"] },
  { name: "Genelia DSouza", popularityScore: 82, aliases: ["Genelia"] },
  { name: "Vidya Balan", popularityScore: 87, aliases: ["Vidya"] },
  { name: "Konkona Sen Sharma", popularityScore: 83, aliases: ["Konkona"] },
  { name: "Radhika Apte", popularityScore: 82, aliases: ["Radhika"] },
  { name: "Swara Bhasker", popularityScore: 80, aliases: ["Swara"] },
  { name: "Kalki Koechlin", popularityScore: 81, aliases: ["Kalki"] },
  { name: "Dimple Kapadia", popularityScore: 85, aliases: ["Dimple"] },
  { name: "Ratna Pathak Shah", popularityScore: 83, aliases: ["Ratna"] },
  { name: "Shefali Shah", popularityScore: 83, aliases: ["Shefali"] },
  { name: "Neena Gupta", popularityScore: 84, aliases: ["Neena"] },
  { name: "Gajraj Rao", popularityScore: 81, aliases: ["Gajraj"] },
  { name: "Jitendra Kumar", popularityScore: 82, aliases: ["Jeetu", "Jitendra"] },
  { name: "Vijay Raaz", popularityScore: 81, aliases: ["Vijay"] },
  { name: "Deepak Dobriyal", popularityScore: 80, aliases: ["Deepak"] },
  { name: "Sanjay Mishra", popularityScore: 82, aliases: ["Sanjay M"] },
  { name: "Shabana Azmi", popularityScore: 86, aliases: ["Shabana"] },
  { name: "Jaya Bachchan", popularityScore: 85, aliases: ["Jaya"] },
  { name: "Waheeda Rehman", popularityScore: 85, aliases: ["Waheeda"] },
  { name: "Asha Parekh", popularityScore: 83, aliases: ["Asha"] },
  { name: "Helen", popularityScore: 84, aliases: ["Helen"] },
  { name: "Farida Jalal", popularityScore: 83, aliases: ["Farida"] },
  { name: "Kirron Kher", popularityScore: 81, aliases: ["Kirron"] },
  { name: "Smita Patil", popularityScore: 84, aliases: ["Smita"] },
  { name: "Nandita Das", popularityScore: 82, aliases: ["Nandita"] },
  { name: "Divya Dutta", popularityScore: 81, aliases: ["Divya"] },
  { name: "Tisca Chopra", popularityScore: 80, aliases: ["Tisca"] },
  { name: "Amrita Singh", popularityScore: 82, aliases: ["Amrita"] },
  { name: "Mahima Chaudhry", popularityScore: 80, aliases: ["Mahima"] },
  { name: "Gracy Singh", popularityScore: 79, aliases: ["Gracy"] },
  { name: "Bhagyashree", popularityScore: 80, aliases: ["Bhagyashree"] },
  { name: "Dharmendra", popularityScore: 88, aliases: ["Dharmendra", "Dharm ji"] },
  { name: "Rishi Kapoor", popularityScore: 89, aliases: ["Rishi", "Chintu"] },
  { name: "Amrish Puri", popularityScore: 86, aliases: ["Amrish", "Mogambo"] },
  { name: "Anil Kapoor", popularityScore: 87, aliases: ["Anil", "Jhakaas"] },
  { name: "Jackie Shroff", popularityScore: 85, aliases: ["Jackie", "Bhidu"] },
  { name: "Mithun Chakraborty", popularityScore: 85, aliases: ["Mithun", "Mithunda"] },
  { name: "Govinda", popularityScore: 86, aliases: ["Govinda", "Chi Chi"] },
  { name: "Shakti Kapoor", popularityScore: 82, aliases: ["Shakti"] },
  { name: "Kader Khan", popularityScore: 83, aliases: ["Kader"] },
  { name: "Asrani", popularityScore: 81, aliases: ["Asrani"] },
  { name: "Rajpal Yadav", popularityScore: 81, aliases: ["Rajpal"] },
  { name: "Kay Kay Menon", popularityScore: 82, aliases: ["Kay Kay"] },
  { name: "Vinay Pathak", popularityScore: 81, aliases: ["Vinay"] },
  { name: "Ranvir Shorey", popularityScore: 80, aliases: ["Ranvir"] },
  { name: "Saurabh Shukla", popularityScore: 82, aliases: ["Saurabh"] },
  { name: "Ronit Roy", popularityScore: 81, aliases: ["Ronit"] },
  { name: "Rajat Kapoor", popularityScore: 80, aliases: ["Rajat"] },
  { name: "Aparshakti Khurana", popularityScore: 80, aliases: ["Aparshakti"] },
  { name: "Mohammed Zeeshan Ayyub", popularityScore: 79, aliases: ["Zeeshan"] },
  { name: "Kunal Khemu", popularityScore: 80, aliases: ["Kunal"] },
  { name: "Sharman Joshi", popularityScore: 82, aliases: ["Sharman"] },
  { name: "R Madhavan", popularityScore: 84, aliases: ["Madhavan"] },
  { name: "Arjun Rampal", popularityScore: 83, aliases: ["Arjun"] },
  { name: "Zayed Khan", popularityScore: 77, aliases: ["Zayed"] },
  { name: "Fardeen Khan", popularityScore: 78, aliases: ["Fardeen"] },
  { name: "Tusshar Kapoor", popularityScore: 79, aliases: ["Tusshar"] },
  { name: "Aftab Shivdasani", popularityScore: 78, aliases: ["Aftab"] },
  { name: "Uday Chopra", popularityScore: 77, aliases: ["Uday"] },
  { name: "Jimmy Sheirgill", popularityScore: 80, aliases: ["Jimmy"] },
  { name: "Ali Zafar", popularityScore: 79, aliases: ["Ali Z"] },
  { name: "Aditya Roy Kapur", popularityScore: 81, aliases: ["Aditya"] },
  { name: "Abhay Deol", popularityScore: 80, aliases: ["Abhay"] },
  { name: "Farhan Akhtar", popularityScore: 83, aliases: ["Farhan"] },
  { name: "Arjun Kapoor", popularityScore: 81, aliases: ["Arjun K"] },
  { name: "Sushant Singh Rajput", popularityScore: 86, aliases: ["Sushant", "SSR"] },
  { name: "Diljit Dosanjh", popularityScore: 82, aliases: ["Diljit"] },
  { name: "Sunny Singh", popularityScore: 78, aliases: ["Sunny S"] },
  { name: "Nushrratt Bharuccha", popularityScore: 79, aliases: ["Nushrratt"] },
  { name: "Huma Qureshi", popularityScore: 80, aliases: ["Huma"] },
  { name: "Yami Gautam", popularityScore: 81, aliases: ["Yami"] },
  { name: "Nargis Fakhri", popularityScore: 78, aliases: ["Nargis"] },
  { name: "Vaani Kapoor", popularityScore: 79, aliases: ["Vaani"] },
  { name: "Mrunal Thakur", popularityScore: 80, aliases: ["Mrunal"] },
  { name: "Sanya Malhotra", popularityScore: 81, aliases: ["Sanya"] },
  { name: "Fatima Sana Shaikh", popularityScore: 79, aliases: ["Fatima"] },
  { name: "Zaira Wasim", popularityScore: 78, aliases: ["Zaira"] },
  { name: "Rashmika Mandanna", popularityScore: 82, aliases: ["Rashmika"] },
  { name: "Nayanthara", popularityScore: 83, aliases: ["Nayanthara", "Nayan"] },
  { name: "Tripti Dimri", popularityScore: 80, aliases: ["Tripti"] },
  { name: "Nimrat Kaur", popularityScore: 79, aliases: ["Nimrat"] },
  { name: "Samantha Ruth Prabhu", popularityScore: 82, aliases: ["Samantha"] },
  { name: "Tamannaah Bhatia", popularityScore: 81, aliases: ["Tamannaah"] },
  { name: "Kajal Aggarwal", popularityScore: 80, aliases: ["Kajal"] },
  { name: "Rakul Preet Singh", popularityScore: 79, aliases: ["Rakul"] },
  { name: "Pooja Hegde", popularityScore: 80, aliases: ["Pooja H"] },
  { name: "Nora Fatehi", popularityScore: 81, aliases: ["Nora"] },
  { name: "Prabhas", popularityScore: 88, aliases: ["Prabhas"] },
  { name: "Ram Charan", popularityScore: 82, aliases: ["Ram Charan"] },
  { name: "N T Rama Rao Jr", popularityScore: 83, aliases: ["NTR", "Jr NTR"] },
  { name: "Allu Arjun", popularityScore: 85, aliases: ["Allu Arjun", "Bunny"] },
  { name: "Mahesh Babu", popularityScore: 84, aliases: ["Mahesh Babu"] },
  { name: "Vijay Deverakonda", popularityScore: 81, aliases: ["Vijay D"] },
  { name: "Dulquer Salmaan", popularityScore: 82, aliases: ["Dulquer"] },
  { name: "Fahadh Faasil", popularityScore: 80, aliases: ["Fahadh"] },
  { name: "Rana Daggubati", popularityScore: 79, aliases: ["Rana"] },
  { name: "Naga Chaitanya", popularityScore: 78, aliases: ["Chay"] },
  { name: "Vijay Sethupathi", popularityScore: 82, aliases: ["Vijay S"] },
  { name: "Suriya", popularityScore: 83, aliases: ["Suriya"] },
  { name: "Karthi", popularityScore: 80, aliases: ["Karthi"] },
  { name: "Dhanush", popularityScore: 84, aliases: ["Dhanush"] },
  { name: "Sivakarthikeyan", popularityScore: 79, aliases: ["SK"] },
];

export const seedMovies = [
  { title: "Dilwale Dulhania Le Jayenge", releaseYear: 1995, region: "hindi", genre: "romance", aliases: ["DDLJ"], cast: ["Shah Rukh Khan", "Kajol", "Amrish Puri", "Farida Jalal"] },
  { title: "Kuch Kuch Hota Hai", releaseYear: 1998, region: "hindi", genre: "romance", aliases: ["KKHH"], cast: ["Shah Rukh Khan", "Kajol", "Rani Mukerji", "Salman Khan"] },
  { title: "Dil To Pagal Hai", releaseYear: 1997, region: "hindi", genre: "romance", cast: ["Shah Rukh Khan", "Madhuri Dixit", "Karishma Kapoor"] },
  { title: "Hum Aapke Hain Koun", releaseYear: 1994, region: "hindi", genre: "romance", aliases: ["HAHK"], cast: ["Salman Khan", "Madhuri Dixit"] },
  { title: "Andaz Apna Apna", releaseYear: 1994, region: "hindi", genre: "comedy", cast: ["Aamir Khan", "Salman Khan", "Raveena Tandon", "Karishma Kapoor", "Paresh Rawal"] },
  { title: "Rangeela", releaseYear: 1995, region: "hindi", genre: "romance", cast: ["Aamir Khan", "Urmila Matondkar", "Jackie Shroff"] },
  { title: "Raja Hindustani", releaseYear: 1996, region: "hindi", genre: "romance", cast: ["Aamir Khan", "Karishma Kapoor", "Johnny Lever"] },
  { title: "Sarfarosh", releaseYear: 1999, region: "hindi", genre: "action", cast: ["Aamir Khan", "Naseeruddin Shah"] },
  { title: "Hum Dil De Chuke Sanam", releaseYear: 1999, region: "hindi", genre: "romance", cast: ["Salman Khan", "Aishwarya Rai Bachchan", "Ajay Devgn"] },
  { title: "Biwi No 1", releaseYear: 1999, region: "hindi", genre: "comedy", cast: ["Salman Khan", "Karishma Kapoor", "Sushmita Sen", "Anil Kapoor"] },
  { title: "Karan Arjun", releaseYear: 1995, region: "hindi", genre: "action", cast: ["Shah Rukh Khan", "Salman Khan", "Kajol", "Amrish Puri"] },
  { title: "Mohabbatein", releaseYear: 2000, region: "hindi", genre: "romance", cast: ["Shah Rukh Khan", "Amitabh Bachchan", "Aishwarya Rai Bachchan", "Uday Chopra"] },
  { title: "Kabhi Khushi Kabhie Gham", releaseYear: 2001, region: "hindi", genre: "drama", aliases: ["K3G"], cast: ["Shah Rukh Khan", "Amitabh Bachchan", "Jaya Bachchan", "Kajol", "Hrithik Roshan", "Kareena Kapoor Khan", "Rani Mukerji"] },
  { title: "Devdas", releaseYear: 2002, region: "hindi", genre: "romance", cast: ["Shah Rukh Khan", "Aishwarya Rai Bachchan", "Madhuri Dixit", "Jackie Shroff"] },
  { title: "Kal Ho Naa Ho", releaseYear: 2003, region: "hindi", genre: "romance", cast: ["Shah Rukh Khan", "Preity Zinta", "Saif Ali Khan", "Jaya Bachchan"] },
  { title: "Veer-Zaara", releaseYear: 2004, region: "hindi", genre: "romance", cast: ["Shah Rukh Khan", "Preity Zinta", "Rani Mukerji", "Amitabh Bachchan", "Hema Malini"] },
  { title: "Swades", releaseYear: 2004, region: "hindi", genre: "drama", cast: ["Shah Rukh Khan"] },
  { title: "Chak De India", releaseYear: 2007, region: "hindi", genre: "sports", cast: ["Shah Rukh Khan"] },
  { title: "Om Shanti Om", releaseYear: 2007, region: "hindi", genre: "drama", cast: ["Shah Rukh Khan", "Deepika Padukone", "Arjun Rampal", "Shreyas Talpade"] },
  { title: "Rab Ne Bana Di Jodi", releaseYear: 2008, region: "hindi", genre: "romance", cast: ["Shah Rukh Khan", "Anushka Sharma", "Vinay Pathak"] },
  { title: "My Name Is Khan", releaseYear: 2010, region: "hindi", genre: "drama", cast: ["Shah Rukh Khan", "Kajol"] },
  { title: "Chennai Express", releaseYear: 2013, region: "hindi", genre: "comedy", cast: ["Shah Rukh Khan", "Deepika Padukone", "Nikitin Dheer"] },
  { title: "Happy New Year", releaseYear: 2014, region: "hindi", genre: "comedy", cast: ["Shah Rukh Khan", "Deepika Padukone", "Abhishek Bachchan", "Boman Irani", "Sonu Sood", "Vivaan Shah"] },
  { title: "Dilwale", releaseYear: 2015, region: "hindi", genre: "action", cast: ["Shah Rukh Khan", "Kajol", "Varun Dhawan", "Kriti Sanon"] },
  { title: "Dear Zindagi", releaseYear: 2016, region: "hindi", genre: "drama", cast: ["Shah Rukh Khan", "Alia Bhatt", "Ali Zafar", "Kunal Kapoor"] },
  { title: "Raees", releaseYear: 2017, region: "hindi", genre: "action", cast: ["Shah Rukh Khan", "Nawazuddin Siddiqui"] },
  { title: "Zero", releaseYear: 2018, region: "hindi", genre: "drama", cast: ["Shah Rukh Khan", "Anushka Sharma", "Katrina Kaif"] },
  { title: "Pathaan", releaseYear: 2023, region: "hindi", genre: "action", cast: ["Shah Rukh Khan", "Deepika Padukone", "John Abraham", "Dimple Kapadia"] },
  { title: "Jawan", releaseYear: 2023, region: "hindi", genre: "action", cast: ["Shah Rukh Khan", "Nayanthara", "Vijay Sethupathi", "Deepika Padukone"] },
  { title: "Dunki", releaseYear: 2023, region: "hindi", genre: "drama", cast: ["Shah Rukh Khan", "Taapsee Pannu", "Boman Irani", "Vicky Kaushal"] },
  { title: "Maine Pyar Kiya", releaseYear: 1989, region: "hindi", genre: "romance", cast: ["Salman Khan", "Bhagyashree"] },
  { title: "Tere Naam", releaseYear: 2003, region: "hindi", genre: "romance", cast: ["Salman Khan"] },
  { title: "Mujhse Shaadi Karogi", releaseYear: 2004, region: "hindi", genre: "comedy", cast: ["Salman Khan", "Priyanka Chopra", "Akshay Kumar"] },
  { title: "No Entry", releaseYear: 2005, region: "hindi", genre: "comedy", cast: ["Salman Khan", "Anil Kapoor", "Fardeen Khan", "Bipasha Basu", "Lara Dutta", "Esha Deol"] },
  { title: "Partner", releaseYear: 2007, region: "hindi", genre: "comedy", cast: ["Salman Khan", "Govinda", "Lara Dutta", "Katrina Kaif"] },
  { title: "Wanted", releaseYear: 2009, region: "hindi", genre: "action", cast: ["Salman Khan", "Ayesha Takia", "Prakash Raj"] },
  { title: "Dabangg", releaseYear: 2010, region: "hindi", genre: "action", cast: ["Salman Khan", "Sonakshi Sinha", "Sonu Sood", "Arbaaz Khan"] },
  { title: "Bodyguard", releaseYear: 2011, region: "hindi", genre: "action", cast: ["Salman Khan", "Kareena Kapoor Khan"] },
  { title: "Ek Tha Tiger", releaseYear: 2012, region: "hindi", genre: "action", cast: ["Salman Khan", "Katrina Kaif", "Ranvir Shorey"] },
  { title: "Bajrangi Bhaijaan", releaseYear: 2015, region: "hindi", genre: "drama", cast: ["Salman Khan", "Kareena Kapoor Khan", "Nawazuddin Siddiqui", "Harshaali Malhotra"] },
  { title: "Sultan", releaseYear: 2016, region: "hindi", genre: "sports", cast: ["Salman Khan", "Anushka Sharma", "Randeep Hooda"] },
  { title: "Tiger Zinda Hai", releaseYear: 2017, region: "hindi", genre: "action", cast: ["Salman Khan", "Katrina Kaif"] },
  { title: "Bharat", releaseYear: 2019, region: "hindi", genre: "drama", cast: ["Salman Khan", "Katrina Kaif", "Disha Patani", "Sunil Grover"] },
  { title: "Dabangg 3", releaseYear: 2019, region: "hindi", genre: "action", cast: ["Salman Khan", "Sonakshi Sinha"] },
  { title: "Qayamat Se Qayamat Tak", releaseYear: 1988, region: "hindi", genre: "romance", cast: ["Aamir Khan", "Juhi Chawla"] },
  { title: "Dil", releaseYear: 1990, region: "hindi", genre: "romance", cast: ["Aamir Khan", "Madhuri Dixit", "Anupam Kher"] },
  { title: "Lagaan", releaseYear: 2001, region: "hindi", genre: "sports", cast: ["Aamir Khan", "Gracy Singh"] },
  { title: "Dil Chahta Hai", releaseYear: 2001, region: "hindi", genre: "drama", cast: ["Aamir Khan", "Saif Ali Khan", "Akshaye Khanna", "Preity Zinta", "Dimple Kapadia"] },
  { title: "Rang De Basanti", releaseYear: 2006, region: "hindi", genre: "drama", cast: ["Aamir Khan", "Sharman Joshi", "Kunal Kapoor", "Atul Kulkarni", "Soha Ali Khan", "Alice Patten", "Madhavan"] },
  { title: "Taare Zameen Par", releaseYear: 2007, region: "hindi", genre: "drama", cast: ["Aamir Khan", "Darsheel Safary", "Tisca Chopra", "Vipin Sharma"] },
  { title: "Ghajini", releaseYear: 2008, region: "hindi", genre: "action", cast: ["Aamir Khan", "Asin", "Jiah Khan"] },
  { title: "3 Idiots", releaseYear: 2009, region: "hindi", genre: "comedy", cast: ["Aamir Khan", "Kareena Kapoor Khan", "R Madhavan", "Sharman Joshi", "Boman Irani", "Omi Vaidya"] },
  { title: "Talaash", releaseYear: 2012, region: "hindi", genre: "thriller", cast: ["Aamir Khan", "Kareena Kapoor Khan", "Rani Mukerji", "Nawazuddin Siddiqui"] },
  { title: "Dhoom 3", releaseYear: 2013, region: "hindi", genre: "action", cast: ["Aamir Khan", "Katrina Kaif", "Abhishek Bachchan", "Uday Chopra"] },
  { title: "PK", releaseYear: 2014, region: "hindi", genre: "comedy", cast: ["Aamir Khan", "Anushka Sharma", "Sushant Singh Rajput", "Boman Irani", "Sanjay Dutt"] },
  { title: "Dangal", releaseYear: 2016, region: "hindi", genre: "sports", cast: ["Aamir Khan", "Sakshi Tanwar", "Fatima Sana Shaikh", "Sanya Malhotra", "Zaira Wasim"] },
  { title: "Secret Superstar", releaseYear: 2017, region: "hindi", genre: "drama", cast: ["Aamir Khan", "Zaira Wasim", "Meher Vij", "Raj Arjun"] },
  { title: "Thugs of Hindostan", releaseYear: 2018, region: "hindi", genre: "action", cast: ["Aamir Khan", "Amitabh Bachchan", "Katrina Kaif", "Fatima Sana Shaikh"] },
  { title: "Laal Singh Chaddha", releaseYear: 2022, region: "hindi", genre: "drama", cast: ["Aamir Khan", "Kareena Kapoor Khan", "Naga Chaitanya", "Mona Singh"] },
  { title: "Sholay", releaseYear: 1975, region: "hindi", genre: "action", cast: ["Amitabh Bachchan", "Dharmendra", "Hema Malini", "Sanjeev Kumar", "Jaya Bachchan", "Amjad Khan"] },
  { title: "Deewaar", releaseYear: 1975, region: "hindi", genre: "action", cast: ["Amitabh Bachchan", "Shashi Kapoor", "Nirupa Roy", "Parveen Babi", "Neetu Singh"] },
  { title: "Amar Akbar Anthony", releaseYear: 1977, region: "hindi", genre: "comedy", cast: ["Amitabh Bachchan", "Vinod Khanna", "Rishi Kapoor", "Shabana Azmi", "Neetu Singh", "Parveen Babi"] },
  { title: "Don", releaseYear: 1978, region: "hindi", genre: "action", cast: ["Amitabh Bachchan", "Zeenat Aman", "Pran"] },
  { title: "Muqaddar Ka Sikandar", releaseYear: 1978, region: "hindi", genre: "drama", cast: ["Amitabh Bachchan", "Vinod Khanna", "Rekha", "Rakhee Gulzar", "Amjad Khan"] },
  { title: "Silsila", releaseYear: 1981, region: "hindi", genre: "romance", cast: ["Amitabh Bachchan", "Rekha", "Jaya Bachchan", "Sanjeev Kumar", "Shashi Kapoor"] },
  { title: "Coolie", releaseYear: 1983, region: "hindi", genre: "action", cast: ["Amitabh Bachchan", "Rishi Kapoor", "Rati Agnihotri", "Kader Khan"] },
  { title: "Shahenshah", releaseYear: 1988, region: "hindi", genre: "action", cast: ["Amitabh Bachchan", "Meenakshi Seshadri", "Amrish Puri"] },
  { title: "Agneepath", releaseYear: 1990, region: "hindi", genre: "action", cast: ["Amitabh Bachchan", "Mithun Chakraborty", "Danny Denzongpa", "Rohini Hattangadi"] },
  { title: "Hum", releaseYear: 1991, region: "hindi", genre: "action", cast: ["Amitabh Bachchan", "Rajinikanth", "Govinda", "Kimi Katkar", "Deepa Sahi"] },
  { title: "Black", releaseYear: 2005, region: "hindi", genre: "drama", cast: ["Amitabh Bachchan", "Rani Mukerji", "Ayesha Kapoor"] },
  { title: "Sarkar", releaseYear: 2005, region: "hindi", genre: "drama", cast: ["Amitabh Bachchan", "Abhishek Bachchan", "Katrina Kaif", "Kota Srinivasa Rao"] },
  { title: "Cheeni Kum", releaseYear: 2007, region: "hindi", genre: "romance", cast: ["Amitabh Bachchan", "Tabu", "Paresh Rawal", "Zohra Sehgal"] },
  { title: "Paa", releaseYear: 2009, region: "hindi", genre: "drama", cast: ["Amitabh Bachchan", "Abhishek Bachchan", "Vidya Balan", "Paresh Rawal"] },
  { title: "Piku", releaseYear: 2015, region: "hindi", genre: "comedy", cast: ["Amitabh Bachchan", "Deepika Padukone", "Irrfan Khan", "Moushumi Chatterjee"] },
  { title: "Pink", releaseYear: 2016, region: "hindi", genre: "thriller", cast: ["Amitabh Bachchan", "Taapsee Pannu", "Kirti Kulhari", "Andrea Tariang"] },
  { title: "102 Not Out", releaseYear: 2018, region: "hindi", genre: "comedy", cast: ["Amitabh Bachchan", "Rishi Kapoor", "Jimit Trivedi"] },
  { title: "Badla", releaseYear: 2019, region: "hindi", genre: "thriller", cast: ["Amitabh Bachchan", "Taapsee Pannu", "Amrita Singh", "Tony Luke"] },
  { title: "Gulabo Sitabo", releaseYear: 2020, region: "hindi", genre: "comedy", cast: ["Amitabh Bachchan", "Ayushmann Khurrana", "Vijay Raaz"] },
  { title: "Khiladi", releaseYear: 1992, region: "hindi", genre: "action", cast: ["Akshay Kumar", "Ayesha Jhulka", "Deepak Tijori"] },
  { title: "Main Khiladi Tu Anari", releaseYear: 1994, region: "hindi", genre: "action", cast: ["Akshay Kumar", "Saif Ali Khan", "Shilpa Shetty"] },
  { title: "Mohra", releaseYear: 1994, region: "hindi", genre: "action", cast: ["Akshay Kumar", "Suniel Shetty", "Raveena Tandon", "Naseeruddin Shah"] },
  { title: "Hera Pheri", releaseYear: 2000, region: "hindi", genre: "comedy", cast: ["Akshay Kumar", "Suniel Shetty", "Paresh Rawal", "Tabu"] },
  { title: "Dhadkan", releaseYear: 2000, region: "hindi", genre: "romance", cast: ["Akshay Kumar", "Shilpa Shetty", "Suniel Shetty"] },
  { title: "Ajnabee", releaseYear: 2001, region: "hindi", genre: "thriller", cast: ["Akshay Kumar", "Bobby Deol", "Kareena Kapoor Khan", "Bipasha Basu"] },
  { title: "Awara Paagal Deewana", releaseYear: 2002, region: "hindi", genre: "comedy", cast: ["Akshay Kumar", "Suniel Shetty", "Aftab Shivdasani", "Paresh Rawal", "Om Puri"] },
  { title: "Namastey London", releaseYear: 2007, region: "hindi", genre: "romance", cast: ["Akshay Kumar", "Katrina Kaif", "Rishi Kapoor"] },
  { title: "Singh Is Kinng", releaseYear: 2008, region: "hindi", genre: "comedy", cast: ["Akshay Kumar", "Katrina Kaif", "Sonu Sood", "Neha Dhupia"] },
  { title: "Housefull", releaseYear: 2010, region: "hindi", genre: "comedy", cast: ["Akshay Kumar", "Deepika Padukone", "Riteish Deshmukh", "Lara Dutta", "Arjun Rampal", "Jiah Khan"] },
  { title: "Rowdy Rathore", releaseYear: 2012, region: "hindi", genre: "action", cast: ["Akshay Kumar", "Sonakshi Sinha"] },
  { title: "Special 26", releaseYear: 2013, region: "hindi", genre: "thriller", cast: ["Akshay Kumar", "Kajal Aggarwal", "Manoj Bajpayee", "Jimmy Sheirgill", "Anupam Kher"] },
  { title: "Holiday", releaseYear: 2014, region: "hindi", genre: "action", cast: ["Akshay Kumar", "Sonakshi Sinha", "Govinda", "Sumeet Raghavan"] },
  { title: "Airlift", releaseYear: 2016, region: "hindi", genre: "drama", cast: ["Akshay Kumar", "Nimrat Kaur", "Kumud Mishra", "Prakash Belawadi"] },
  { title: "Rustom", releaseYear: 2016, region: "hindi", genre: "thriller", cast: ["Akshay Kumar", "Ileana DCruz", "Esha Gupta", "Arjan Bajwa"] },
  { title: "Toilet Ek Prem Katha", releaseYear: 2017, region: "hindi", genre: "drama", cast: ["Akshay Kumar", "Bhumi Pednekar", "Divyendu Sharma", "Sudhir Pandey"] },
  { title: "Pad Man", releaseYear: 2018, region: "hindi", genre: "drama", cast: ["Akshay Kumar", "Sonam Kapoor", "Radhika Apte"] },
  { title: "Kesari", releaseYear: 2019, region: "hindi", genre: "war", cast: ["Akshay Kumar", "Parineeti Chopra", "Mir Sarwar"] },
  { title: "Good Newwz", releaseYear: 2019, region: "hindi", genre: "comedy", cast: ["Akshay Kumar", "Kareena Kapoor Khan", "Diljit Dosanjh", "Kiara Advani"] },
  { title: "Sooryavanshi", releaseYear: 2021, region: "hindi", genre: "action", cast: ["Akshay Kumar", "Katrina Kaif", "Ajay Devgn", "Ranveer Singh", "Jackie Shroff"] },
];
